### ISSUE TITLE
Fails for api-doc-template

### ISSUE THREAD

**Issue by lukaspanni** [wirthual/deutschland-generator-action#2]
The action fails on rename generated code if the folder does not exist.
See Logs: https://github.com/lukaspanni/api-doc-template/runs/4657227598 at line 280 and following

**Comment by wirthual** [comment]
Well the reason for it to fail is because it seems a the <Name> placeholder is not a valid folder/package name. 

To run the test, you would need to use a valid name/version number for the generation to work.

**Comment by lukaspanni** [comment]
I thought that it was a problem with the script not checking if the file exists
